### ISSUE TITLE
Data storage/GDPR/Security

### ISSUE THREAD

**Issue by tatianamac** [tatianamac/devsofcolour#3]
### Initial thoughts on data storage/GDPR/Security

- Store as little information as possible
- Connect to other places for messaging (so no message retention/communication management)
- **Require** as little information as possible (so, no phone number necessary bullshit)
- I don't know GDPR (YANKEE) very well but we'll want to consider that

### Questions

- How necessary are real names? (I don't think they are.)
- Can we make all references gender neutral so that we can make gender pronouns an optional designation?
- I love the idea of having a way folks can self-select that they're queer/disabled if they want to to support intersectionality. Not a question, I guess, moreso, how do we do this in a good way?
- How can we make it easy and clear to offboard and make our information collecting as transparent as possible?

**Comment by Andy-set-studio** [comment]
## My thoughts on your initial thoughts

- Hell yeh
- I think all we should do is present info for people and help them get discovered. The rest is up to whatever they like to use IMO
- Yep! 
- From what we've been discussing so far, we should be fine. Also, with the data being provided to us via open source means will protect us from liability in most cases (I think) 

## Answers
- Not at all IMO (let's go back to 1999) 
- Neutralise all the things
- Maybe tagging with hints from us? 
- With it being 100% open source, there's no hiding anything (we're even speccing it out in the open)

**Comment by taurean** [comment]
I agree with all of this so far as well. I think we can:
1. decide on _what_ information we want to allow people to display as well as determine what is optional and what isn't
2. from there decide how that should be presented to site visitors (and how the layout changes to support optional info that isn't used). 
3. Having those designs can then help us structure the yaml/html/whatever to properly support those options (eg. helpful to know if something is boolean vs a string, etc)

**Comment by Andy-set-studio** [comment]
Yeh I'm totally on board with this approach @taurean 👍

**Comment by tatianamac** [comment]
Do we feel as though we have sufficient information given what we determined in the 'profile info' issue?

What more do we need on this front? [Trying to close tickets and convert them into tasks as needed]

**Comment by Andy-set-studio** [comment]
I think we just need a card in the project that links out to this discussion 🙂
