### ISSUE TITLE
Spin up Site

### ISSUE THREAD

**Issue by BboyAkers** [tatianamac/devsofcolour#5]

**Comment by tatianamac** [comment]
Added you! 

@taurean @andybelldesign Austin has volunteered to help out. Maybe you can introduce yourself, Austin, and we can figure out where you fit in best with our skillsets to start divying up and creating more tasks?

So far, we're looking to build a lean database upon a SSG, like Eleventy, where devs can issue pull requests to be added. Most of our conversations to date have been around security of users, making it relatively easy, and ensuring that elements are searchable.

**Comment by taurean** [comment]
Idk how I missed this. Hey @bboyakers!
