### ISSUE TITLE
Where can I find this?

### ISSUE THREAD

**Issue by o-az** [tatianamac/devsofcolour#6]
the repo is empty. Has it moved somewhere or was this never a thing?

**Comment by BboyAkers** [comment]
It is, we're getting things up and running. We've all been crazy busy with work and other open source stuff.

**Comment by truedat101** [comment]
Excited that this is happening and a network is being organized, and that this is getting attention.  But, link?  I'm considering sponsorship but like, would like to see the goods.

**Comment by tatianamac** [comment]
@Omar-Aziz and @truedat101 : We're in the process of building this, which you can see through the other open issues. Totally understand wanting to hold off sponsorship until you can see the database. We'll announce things on the Twitter account as they become live (https://www.twitter.com/DevsofColour)
